# configs/config.yaml

experiment:
 # name: "baseline_cnn_awgn_sigma25"
  name: "dncnn_awgn_sigma5"
  output_dir: "./checkpoints_dncnn_awgn_sigma5"

model:
  #name: "baseline_cnn"           # Options: baseline_cnn, dncnn, restormer, etc.
  name: "dncnn"           # Options: baseline_cnn, dncnn, restormer, etc.
  params:
    in_channels: 3
    out_channels: 3
    num_layers: 17
    num_features: 64

dataset:
  train_dir: "../../CBSD68-dataset/noisy5/train"  # Moves up two folders, then into data/train
  val_dir: "../../CBSD68-dataset/noisy5/val"      # Moves up two folders, then into data/val
  patch_size: 128
  sigma: 25.0             # Additive White Gaussian Noise std (0-255)
  test_split: 0.1   # 10% of training data used for testing

training:
  epochs: 20
  batch_size: 16
  learning_rate: 0.001
  loss: "MSE"              # Options: L1, MSE
  num_workers: 2

hardware:
  device: "auto"          # Options: auto, xpu, cuda, cpu